import { Link } from "@/i18n/navigation";
import {
  LEGAL_CONTACT,
  LegalDocumentContent,
  LegalLink,
  LegalList,
  LegalTable,
} from "@/components/legal/LegalDocument";

export const privacyEn: LegalDocumentContent = {
  meta: {
    title: "Privacy policy",
    description:
      "How Joutes collects, uses and protects your personal data: data processed, purposes, recipients, retention periods and how to exercise your rights.",
    keywords: ["privacy policy", "personal data", "gdpr", "privacy", "cookies", "joutes"],
  },
  documentLabel: "Legal document",
  title: "Privacy policy",
  description:
    "What data Joutes collects, why, who it is shared with and how to stay in control of it.",
  lastUpdated: (date) => `Last updated: ${date}`,
  crossLinks: (
    <>
      See also the{" "}
      <Link href="/cgu" className="text-primary hover:underline">
        terms of use
      </Link>
      .
    </>
  ),
  translationNotice: (
    <p>
      This English version is a courtesy translation. The{" "}
      <strong>French version is the legally binding one</strong>: in the event of any discrepancy,
      the French text prevails.
    </p>
  ),
  highlightTitle: "In short",
  highlight: (
    <ul className="list-disc space-y-2 pl-6">
      <li>We only collect what the Platform needs to work.</li>
      <li>Your data is never sold, rented or used for advertising.</li>
      <li>No advertising cookies and no profiling trackers: audience measurement is anonymous.</li>
      <li>
        Your location is only used if you provide it, to find events near you.
      </li>
      <li>You can access, correct, export or have your data deleted at any time.</li>
    </ul>
  ),
  summaryTitle: "Contents",
  articles: [
    {
      id: "responsable",
      title: "Who processes your data",
      content: (
        <>
          <p>
            The Joutes platform, available at{" "}
            <a href="https://joutes.app" className="text-primary hover:underline">
              https://joutes.app
            </a>
            , is published by Nakasar, acting as data controller for the data described in this
            policy.
          </p>
          <p>
            This policy applies to all the services of the Platform: website, public API, MCP
            server and Discord bot. It supplements the{" "}
            <Link href="/cgu" className="text-primary hover:underline">
              terms of use
            </Link>
            .
          </p>
          <p>
            For any question or request about your data, the contact channels are listed at the end
            of this document.
          </p>
        </>
      ),
    },
    {
      id: "donnees",
      title: "Data we collect",
      content: (
        <>
          <p>
            We only collect the data needed to run the service. Most of it comes directly from you;
            some is generated by your use of the Platform.
          </p>
          <p>
            <strong>Account and authentication</strong>
          </p>
          <LegalList>
            <li>email address;</li>
            <li>one-time sign-in codes, valid for a few minutes, sent by email;</li>
            <li>
              if you sign in with Discord: the ID, username, avatar and email address associated
              with that account;
            </li>
            <li>
              if you use a passkey: the public key and its technical metadata — no biometric data
              is sent to us, it never leaves your device;
            </li>
            <li>
              active sessions: session token, creation and expiry dates, IP address and browser
              used when signing in.
            </li>
          </LegalList>
          <p>
            <strong>Profile and preferences</strong>
          </p>
          <LegalList>
            <li>
              username, display name, description, profile picture, website and social links you
              provide;
            </li>
            <li>friend code, public profile visibility;</li>
            <li>games and venues followed, display language, theme, notification preferences.</li>
          </LegalList>
          <p>
            <strong>Location</strong>
          </p>
          <LegalList>
            <li>
              a default position (latitude and longitude) if you choose to save it in your account;
            </li>
            <li>
              a one-off position, entered manually or provided by your browser after your explicit
              authorisation, used for the duration of a nearby-events search and not stored in the
              database on that occasion.
            </li>
          </LegalList>
          <p>
            <strong>Content and activity</strong>
          </p>
          <LegalList>
            <li>
              events created and registrations, tournaments and leagues (pairings, results,
              standings), matches and play groups;
            </li>
            <li>friends and friend requests, venues followed, membership of private venues;</li>
            <li>collections, wishlists, decks, cubes, trades and sell lists;</li>
            <li>
              community contributions: rulings, errata and the associated votes, quizzes, news,
              content reports;
            </li>
            <li>achievements earned and notifications received.</li>
          </LegalList>
          <p>
            <strong>Integrations and developers</strong>
          </p>
          <LegalList>
            <li>
              API keys: name, description, prefix, date of last use and call counter — the key
              itself is stored hashed;
            </li>
            <li>third-party applications authorised via OAuth and the permissions granted;</li>
            <li>identifiers required for the Discord bot and the MCP server to work.</li>
          </LegalList>
          <p>
            <strong>Technical data</strong>
          </p>
          <LegalList>
            <li>
              logs generated by the hosting provider: IP address, timestamp, resource requested,
              browser and operating system;
            </li>
            <li>
              aggregated audience measurement (pages viewed, referrer) with no identifier that
              could single you out.
            </li>
          </LegalList>
          <p>
            We deliberately collect no special category data within the meaning of Article 9 GDPR.
            Please do not publish any in free-text fields (profile description, event descriptions,
            messages).
          </p>
        </>
      ),
    },
    {
      id: "finalites",
      title: "Why, and on what legal basis",
      content: (
        <>
          <p>
            Each processing operation serves a specific purpose and rests on a legal basis under
            the GDPR:
          </p>
          <LegalTable
            headers={["Purpose", "Data concerned", "Legal basis"]}
            rows={[
              [
                "Creating and managing your account, signing you in",
                "Email, sign-in credentials, sessions, profile",
                "Performance of the Terms (contract)",
              ],
              [
                "Providing the features: events, tournaments, collections, trades, community",
                "The content and activity you create",
                "Performance of the Terms (contract)",
              ],
              [
                "Showing events near you",
                "Saved position or one-off browser position",
                "Consent (withdrawable at any time)",
              ],
              [
                "Sending sign-in emails and service notifications",
                "Email address",
                "Performance of the Terms (contract)",
              ],
              [
                "Sending the weekly digest and Platform news",
                "Email address, games and venues followed",
                "Consent (can be turned off in your preferences)",
              ],
              [
                "Ensuring security, preventing abuse, moderating reported content",
                "Technical logs, reports, account data",
                "Legitimate interest in protecting the service and its users",
              ],
              [
                "Measuring audience and improving the Platform",
                "Aggregated browsing statistics",
                "Legitimate interest (anonymous measurement, no profiling)",
              ],
              [
                "Answering your requests and rights enquiries",
                "Content of the request, account data",
                "Legal obligation",
              ],
            ]}
          />
          <p>
            Your data is never sold, rented or used for targeted advertising, and is not subject to
            any automated decision producing legal effects concerning you.
          </p>
        </>
      ),
    },
    {
      id: "visibilite",
      title: "What other users can see",
      content: (
        <>
          <p>
            Joutes is a community platform: some of your data is, by nature, visible to other
            people.
          </p>
          <LegalList>
            <li>
              <strong>Publicly accessible</strong> (including to search engines): your username and
              avatar wherever they appear on public content, the events you publish, public
              tournaments and their results, community contributions (rulings, errata, quizzes).
            </li>
            <li>
              <strong>Visible if you enable it:</strong> your profile information (description,
              website, social links, games and venues followed) when the public profile is switched
              on in your account.
            </li>
            <li>
              <strong>Visible to a limited circle:</strong> your friends, the members of your play
              groups and private venues, and the participants and organisers of the events you sign
              up for.
            </li>
            <li>
              <strong>Private by default:</strong> your email address, your saved position, your
              collections, wishlists, decks and cubes, as long as you do not share them.
            </li>
          </LegalList>
          <p>
            Event and tournament organisers can see the participant information needed to run the
            event. They are responsible for how they use it outside the Platform.
          </p>
        </>
      ),
    },
    {
      id: "cookies",
      title: "Cookies and audience measurement",
      content: (
        <>
          <p>The Platform deliberately uses very few trackers:</p>
          <LegalList>
            <li>
              <strong>Strictly necessary cookies:</strong> a session cookie that keeps you signed
              in, a language cookie (<code>NEXT_LOCALE</code>) and technical security cookies.
            </li>
            <li>
              <strong>Local storage:</strong> your theme preference (light, dark or system) is kept
              in your browser and is never sent to our servers.
            </li>
            <li>
              <strong>Audience measurement:</strong> Vercel Web Analytics produces aggregated
              traffic statistics without setting an advertising cookie, without a persistent
              identifier and without cross-site tracking.
            </li>
          </LegalList>
          <p>
            We use neither an advertising network nor third-party profiling trackers. This
            processing falls under cookies strictly necessary for the service and anonymous
            audience measurement, both exempt from consent; no cookie banner is therefore shown.
          </p>
          <p>
            You can delete these cookies from your browser at any time; you will be signed out as a
            result.
          </p>
        </>
      ),
    },
    {
      id: "prestataires",
      title: "Hosting and suppliers",
      content: (
        <>
          <p>
            We rely on a limited number of technical suppliers, which act as processors on our
            behalf and do not use your data for their own purposes:
          </p>
          <LegalTable
            headers={["Supplier", "Role", "Data concerned"]}
            rows={[
              [
                "Vercel Inc.",
                "Hosting the Platform, image storage, audience measurement",
                "All data passing through the service, technical logs, published images",
              ],
              ["MongoDB", "Database", "Accounts, profiles, content and activity"],
              [
                "Meilisearch",
                "Search engine for cards and game content",
                "Search queries and game data (no account data)",
              ],
              ["Resend", "Sending emails", "Email address and the content of the message sent"],
              ["OpenAI", "AI-assisted features", "The content you submit to those features"],
              [
                "Discord",
                "Discord sign-in, community bot",
                "Discord ID and profile, messages exchanged with the bot",
              ],
            ]}
          />
          <p>
            Beyond these suppliers, your data is only disclosed to third parties in two cases: to
            the applications you have authorised yourself via OAuth or your API keys, and to
            administrative or judicial authorities where the law requires it.
          </p>
        </>
      ),
    },
    {
      id: "ia",
      title: "AI-assisted features",
      content: (
        <>
          <p>
            Some optional features rely on artificial intelligence models operated by a third-party
            supplier:
          </p>
          <LegalList>
            <li>
              <strong>Card scanning:</strong> the picture you take is sent to the supplier to
              identify the card; it is not stored on our servers.
            </li>
            <li>
              <strong>Deck checking:</strong> the card list submitted is sent for analysis.
            </li>
            <li>
              <strong>Quiz import and event retrieval:</strong> the texts or pages provided are
              sent so that structured information can be extracted from them.
            </li>
          </LegalList>
          <p>
            Only the content needed for the processing is sent, without your identity or contact
            details. That content is not used to train models. If you would rather avoid this
            processing, simply do not use the features concerned.
          </p>
        </>
      ),
    },
    {
      id: "transferts",
      title: "Transfers outside the European Union",
      content: (
        <>
          <p>
            Some of our suppliers are established in the United States or may process data there.
            These transfers are framed by the safeguards provided for in Chapter V of the GDPR, in
            particular the European Commission&apos;s standard contractual clauses and, where
            applicable, the supplier&apos;s Data Privacy Framework certification.
          </p>
          <p>
            You can ask us for details of the safeguards applying to a given supplier through the
            contact channels.
          </p>
        </>
      ),
    },
    {
      id: "conservation",
      title: "Retention periods",
      content: (
        <LegalTable
          headers={["Data", "Period"]}
          rows={[
            [
              "Account, profile and preferences",
              "For as long as the account exists, then deleted or anonymised following your request",
            ],
            [
              "Sign-in sessions",
              "7 days maximum, renewed on use and revocable at any time",
            ],
            ["Sign-in codes sent by email", "10 minutes"],
            [
              "Published content (events, decks, collections, contributions)",
              "Until you delete it or your account is deleted",
            ],
            [
              "Shared histories (tournament results, matches, trades)",
              "Kept for the consistency of other participants' history, dissociated from your account after deletion",
            ],
            ["API keys and application authorisations", "Until they are revoked"],
            [
              "Content reports",
              "For the duration of the review, then a limited period for moderation follow-up",
            ],
            [
              "Technical logs",
              "A short period set by the hosting provider, for security and diagnostics",
            ],
            ["Audience statistics", "Kept in aggregated form, without identification"],
          ]}
        />
      ),
    },
    {
      id: "securite",
      title: "Security",
      content: (
        <>
          <p>We apply measures appropriate to the nature of the service:</p>
          <LegalList>
            <li>encrypted traffic over HTTPS;</li>
            <li>
              passwordless authentication (one-time code, passkey or Discord account), which
              removes the risk tied to password reuse;
            </li>
            <li>hashed storage of API keys and sensitive tokens;</li>
            <li>
              access to production data restricted to the people who need it to operate the
              service;
            </li>
            <li>separation of private data and server-side permission checks.</li>
          </LegalList>
          <p>
            No system is infallible. Should a data breach be likely to result in a high risk to
            your rights and freedoms, you will be informed under the conditions set out in the
            GDPR.
          </p>
        </>
      ),
    },
    {
      id: "droits",
      title: "Your rights",
      content: (
        <>
          <p>
            Under the GDPR and the French Data Protection Act, you have the following rights:
          </p>
          <LegalList>
            <li>
              <strong>Access:</strong> obtain a copy of the data we hold about you;
            </li>
            <li>
              <strong>Rectification:</strong> correct inaccurate data — most information can be
              changed directly from your account;
            </li>
            <li>
              <strong>Erasure:</strong> request the deletion of your account and your data, subject
              to the data we are required to keep;
            </li>
            <li>
              <strong>Objection:</strong> object to processing based on our legitimate interest;
            </li>
            <li>
              <strong>Restriction:</strong> ask for a disputed processing operation to be
              temporarily frozen;
            </li>
            <li>
              <strong>Portability:</strong> receive your data in a structured, machine-readable
              format;
            </li>
            <li>
              <strong>Withdrawal of consent:</strong> at any time, for the processing that depends
              on it (location, optional emails), without affecting processing already carried out;
            </li>
            <li>
              <strong>Post-mortem instructions:</strong> set out what should happen to your data
              after your death.
            </li>
          </LegalList>
          <p>
            To exercise these rights, contact us through the channels listed below. You will
            receive a reply within one month, which may be extended for complex requests. We may
            need to verify your identity, in particular via the email address linked to your
            account.
          </p>
          <p>
            If you believe your rights are not being respected, you can lodge a complaint with the
            French data protection authority (CNIL):{" "}
            <LegalLink href="https://www.cnil.fr">www.cnil.fr</LegalLink>. You may also contact the
            supervisory authority of the EU country where you live.
          </p>
        </>
      ),
    },
    {
      id: "mineurs",
      title: "Minors",
      content: (
        <>
          <p>
            The Platform is intended for people aged 15 or over. Below that age, creating an
            account requires the consent of the holder of parental authority.
          </p>
          <p>
            If you become aware that an account was created by a child without that consent,
            contact us: the account and the associated data will be deleted.
          </p>
        </>
      ),
    },
    {
      id: "modifications",
      title: "Changes to this policy",
      content: (
        <>
          <p>
            This policy may change along with the features of the Platform or the applicable law.
            The date of the latest update appears at the top of the page.
          </p>
          <p>
            Where a change is substantial — a new purpose, a new recipient, a new category of data
            — you will be informed on the Platform or by email before it takes effect, wherever
            this is required.
          </p>
        </>
      ),
    },
    {
      id: "contact",
      title: "Contact",
      content: (
        <>
          <p>For any question about your personal data, or to exercise your rights:</p>
          <LegalList>
            <li>
              <strong>Discord:</strong> <LegalLink href={LEGAL_CONTACT.discord} />
            </li>
            <li>
              <strong>GitHub:</strong> <LegalLink href={LEGAL_CONTACT.github} />
            </li>
          </LegalList>
          <p>
            Please mention the email address linked to your account so that your request can be
            matched to the right user.
          </p>
        </>
      ),
    },
  ],
};
